[all]
# --- overclocking ---
# ARM core frequency in MHz
arm_freq=3000
# VideoCore VII frequency in MHz
gpu_freq=1000
# Voltage offset in microvolts
over_voltage_delta=50000

# --- opengl ---
# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d,composite
# Increase the memory reserved for the GPU
gpu_mem=64
# Avoid GPU down-clocking below 500 MHz that slows FPS down
# v3d_freq_min=500

# --- composite ---
enable_tvout=1
